- src: git+https://github.com/geerlingguy/ansible-role-docker
  version: 6.1.0
  name: geerlingguy.docker
- src: git+https://gitlab.com/etke.cc/roles/swap.git
  version: abfb18b6862108bbf24347500446203170324d7f
- src: git+https://gitlab.com/etke.cc/roles/ssh.git
  version: 237adf859f9270db8a60e720bc4a58164806644e
- src: git+https://gitlab.com/etke.cc/roles/fail2ban.git
  version: 09886730e8d3c061f22d1da4a542899063f97f0a
- src: git+https://github.com/devture/com.devture.ansible.role.docker_sdk_for_python.git
  version: 129c8590e106b83e6f4c259649a613c6279e937a
- src: git+https://github.com/devture/com.devture.ansible.role.playbook_help.git
  version: c1f40e82b4d6b072b6f0e885239322bdaaaf554f
- src: git+https://github.com/devture/com.devture.ansible.role.systemd_docker_base.git
  version: 327d2e17f5189ac2480d6012f58cf64a2b46efba
- src: git+https://github.com/devture/com.devture.ansible.role.timesync.git
  version: 3d5bb2976815958cdce3f368fa34fb51554f899b
- src: git+https://github.com/devture/com.devture.ansible.role.playbook_state_preserver.git
  version: ff2fd42e1c1a9e28e3312bbd725395f9c2fc7f16
- src: git+https://github.com/devture/com.devture.ansible.role.postgres.git
  version: 38764398bf82b06a1736c3bfedc71dfd229e4b52
- src: git+https://github.com/devture/com.devture.ansible.role.postgres_backup.git
  version: 8e9ec48a09284c84704d7a2dce17da35f181574d
- src: git+https://github.com/devture/com.devture.ansible.role.container_socket_proxy.git
  version: v0.1.1-1
- src: git+https://github.com/devture/com.devture.ansible.role.traefik.git
  version: v2.9.9-0
- src: git+https://github.com/devture/com.devture.ansible.role.systemd_service_manager.git
  version: v1.0.0-0
- src: git+https://github.com/devture/com.devture.ansible.role.playbook_runtime_messages.git
  version: 9b4b088c62b528b73a9a7c93d3109b091dd42ec6
- src: git+https://github.com/devture/com.devture.ansible.role.woodpecker_ci_server.git
  version: v0.15.7-3
- src: git+https://github.com/devture/com.devture.ansible.role.woodpecker_ci_agent.git
  version: v0.15.7-1
- src: git+https://gitlab.com/etke.cc/roles/miniflux.git
  version: v2.0.43-2
- src: git+https://gitlab.com/etke.cc/roles/grafana.git
  version: v9.4.7-1
- src: git+https://gitlab.com/etke.cc/roles/radicale.git
  version: v3.1.8.1-2
- src: git+https://gitlab.com/etke.cc/roles/uptime_kuma.git
  version: v1.21.1-0
- src: git+https://gitlab.com/etke.cc/roles/redis.git
  version: v7.0.10-0
- src: git+https://gitlab.com/etke.cc/roles/prometheus_node_exporter.git
  version: v1.5.0-7
- src: git+https://gitlab.com/etke.cc/roles/prometheus_blackbox_exporter.git
  version: v0.23.0-3
- src: git+https://gitlab.com/etke.cc/roles/redmine.git
  version: v5.0.5-1
- src: git+https://gitlab.com/etke.cc/roles/soft_serve.git
  version: v0.4.7-0
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-adguard-home.git
  version: v0.107.26-0
  name: adguard_home
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-aux.git
  version: v1.0.0-0
  name: aux
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-collabora-online.git
  version: v22.05.12.1.1-0
  name: collabora_online
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-docker-registry.git
  version: v2.8.1-1
  name: docker_registry
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-docker-registry-browser.git
  version: v1.6.0-0
  name: docker_registry_browser
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-docker-registry-purger.git
  version: v1.0.0-0
  name: docker_registry_purger
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-focalboard.git
  version: v7.8.0-0
  name: focalboard
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-gitea.git
  version: v1.19.0-0
  name: gitea
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-keycloak.git
  version: v21.0.1-1
  name: keycloak
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-navidrome.git
  version: v0.49.3-1
  name: navidrome
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-netbox.git
  version: v3.4.6-2.5.1-0
  name: netbox
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-nextcloud.git
  version: v26.0.0-1
  name: nextcloud
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-peertube.git
  version: v5.1.0-2
  name: peertube
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-prometheus.git
  version: v2.43.0-0
  name: prometheus
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-syncthing.git
  version: v1.23.2-1
  name: syncthing
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-vaultwarden.git
  version: v1.28.0-0
  name: vaultwarden
- src: git+https://github.com/moan0s/hubsite.git
  version: v1.23.3-1
  name: hubsite
- src: git+https://github.com/moan0s/role-firezone.git
  version: v0.7.25-0
  name: firezone
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-gotosocial.git
  version: v0.7.1-0
  name: gotosocial
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-owncast.git
  version: v0.0.13-0
  name: owncast
